---
title: "About"
---

I am Pu Yuan, a data expert deeply rooted in the fields of finance and economics, with a keen eye for detail and a passion for translating complex data into actionable insights. My educational journey culminated in a Bachelor of Science in Economics and Statistics from the University of Toronto, where I honed my analytical skills and developed a profound understanding of financial models and statistical analysis, graduating with a CGPA of 3.76/4.00.

My professional experience is diverse, stretching from consulting internships at prestigious firms like BCG in Shanghai to analytical roles in the banking sector at Citibank. At BCG, I took the lead on finance consulting projects, applying my expertise in Python, SQL, VBA, R, MATLAB, and Tableau to deliver high-quality, data-driven solutions that exceeded our clients' expectations. My work included utilizing machine learning models to forecast market trends in the automotive aftermarket and conducting comprehensive valuations of companies to inform investment strategies.

As a Credit Analyst Intern at Citibank, I enhanced the credit risk framework, employing sophisticated models that significantly improved prediction accuracy and reduced defaults. My ability to translate complex business requirements into effective data processing and analysis strategies was key in this role.

My tenure as a Data Analyst Intern at Yanc Data Consulting Firm allowed me to spearhead the development of predictive models for loan default probabilities, further showcasing my capability to work with large datasets and implement robust statistical methods for real-world applications.

Beyond these roles, my commitment to my field is also demonstrated through my academic and extracurricular accomplishments. I secured 1st place in the Global Social Entrepreneurship Competition and was the runner-up in the Financial Planning Competition at Morgan Stanley Wealth Management, which validated my financial acumen and entrepreneurial spirit. My research on the COVID-19 pandemic's impact on stock market efficiency and the economic implications of color trends on mental health conditions are testaments to my curiosity and dedication to exploring the intersection of data, economics, and societal trends.

I am a collaborative team player, known for my strong technical and interpersonal skills, developed through rigorous academic training, professional experiences, and a genuine interest in solving complex problems. My journey is one of continuous learning, seeking to leverage my skills in data analysis and financial modeling to make meaningful contributions to the field of economics and finance.

[My CV](Pu Yuan_cv.pdf)
